---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
.libPaths("C:/Users/Public/Downloads")
library(flexdashboard)
library(here)
library(tidyverse)

library(tidycensus)
options(tigris_use_cache = TRUE)

library(scales)
library(leaflet)
library(cowplot)
library(units)
library(sf)
library(leaflet)


## Null Theme
theme_null <- function() {
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.line = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_line(colour = 'transparent'),
        panel.grid.minor = element_blank())
}

counties <- read.csv(here::here("census/Access/R/nc_counties.csv"))
counties <- counties %>% 
  filter(WNC == 1)

## You'll need to get your own API key
census_api_key("c691b7757fc98df81fb556bb6f5b98498f0b8f60")

## See variables
acs_vars <- load_variables(2016, "acs5", cache = TRUE)


get_vars <- data.frame( name = c(
  "B01003_001E", # Total Population
  
  "B02001_001E", # Race/Ethnicity
  "B03002_003E",
  "B03002_004E",
  "B03002_005E",
  "B03002_006E",
  "B03002_007E",
  "B03002_008E",
  "B03002_010E",
  "B03002_011E",
  "B03002_012E",
  
  "B07204_002E", # Different house in United States 1 year ago
  
  "B08301_001E", # MEANS OF TRANSPORTATION TO WORK TOTAL
  "B08301_010E", # Public transportation (excluding taxicab)
  
  "B08601_001E", # MEANS OF TRANSPORTATION TO WORK GEOGRAPHY) TOTAL
  "B08601_010E", # Public transportation (excluding taxicab)
  
  "B15003_001E", # Education
  "B15003_002E",
  "B15003_003E",
  "B15003_004E",
  "B15003_005E",
  "B15003_006E",
  "B15003_007E",
  "B15003_008E",
  "B15003_009E",
  "B15003_010E",
  "B15003_011E",
  "B15003_012E",
  "B15003_013E",
  "B15003_014E",
  "B15003_015E",
  "B15003_016E",
  "B15003_017E",
  "B15003_018E",
  'B15003_019E',
  'B15003_020E',
  'B15003_021E',
  'B15003_022E',
  'B15003_023E',
  'B15003_024E',
  'B15003_025E',
  
  'B17026_001E', # RATIO OF INCOME TO POVERTY LEVEL OF FAMILIES IN THE PAST 12 MONTHS
  'B17026_002E',
  'B17026_003E',
  'B17026_004E',
  'B17026_005E',
  'B17026_006E',
  'B17026_007E',
  'B17026_008E',
  'B17026_009E',
  'B17026_010E',
  'B17026_011E',
  'B17026_012E',
  'B17026_013E',
  
  'B19001_001E', # HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)
  'B19001_002E',
  'B19001_003E',
  'B19001_004E',
  'B19001_005E',
  'B19001_006E',
  'B19001_007E',
  'B19001_008E',
  'B19001_009E',
  'B19001_010E',
  'B19001_011E',
  'B19001_012E',
  'B19001_013E',
  'B19001_014E',
  'B19001_015E',
  'B19001_016E',
  'B19001_017E',
  
  "B19013_001E", #MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)
  
  "B23025_001E", # EMPLOYMENT STATUS FOR THE POPULATION 16 YEARS AND OVER
  "B23025_002E",
  "B23025_003E",
  "B23025_005E",
  "B23025_006E",
  "B23025_007E",
  
  "B25001_001E", # HOUSING UNITS
  "B25002_001E",
  "B25002_002E",
  "B25002_003E",
  
  "B25003_001E", # HOUSING TENURE
  "B25003_002E",
  "B25003_003E",
  "B25035_001E",
  
  "C17002_001E", # RATIO OF INCOME TO POVERTY LEVEL IN THE PAST 12 MONTHS
  "C17002_002E",
  "C17002_003E",
  "C17002_004E",
  "C17002_005E",
  "C17002_006E",
  "C17002_007E",
  "C17002_008E"
))

get_vars <- get_vars %>%
  left_join(acs_vars, by = "name")

# Clean up
get_vars$label <- gsub("Estimate|!|,|\\$", "", get_vars$label)
get_vars$label <- ifelse(get_vars$label != "Total", gsub("Total", "", get_vars$label), get_vars$label)
get_vars$label <- gsub("\\(([^\\)]+)\\)||Civilian labor force", "", get_vars$label)
get_vars$concept <- gsub("\\(([^\\)]+)\\)", "", get_vars$concept)
get_vars$label <- tolower(get_vars$label)
get_vars$concept <- tolower(get_vars$concept)
get_vars$label <- gsub(" ", "_", get_vars$label)
get_vars$concept <- gsub(" ", "_", get_vars$concept)
get_vars$label <- paste(get_vars$concept, get_vars$label, sep = "_")
get_vars$concept <- NULL

## ZCTA
# Close to Zip Code
zcta_county_match <- read.table(here::here("census/Access/R/zcta_county_rel_10.txt"), # Get this file from census website
                                header = TRUE, sep = ",")

zcta_county_match <- zcta_county_match[zcta_county_match$STATE == 37 &
                                         zcta_county_match$COUNTY %in% counties$COUNTYFP, ]

start_time <- Sys.time()
wnc_zcta_data <- get_acs(geography = "zip code tabulation area",
                         variables = get_vars$name,
                         geometry = TRUE,
                         output = "wide")
Sys.time() - start_time
# 2 mins

wnc_zcta_data <- wnc_zcta_data[wnc_zcta_data$GEOID %in% zcta_county_match$ZCTA5,
                               names(wnc_zcta_data) %in% c("NAME", "GEOID", "geometry", get_vars$name)]

## Counties
wnc_county_data <- reduce(
  map(counties$COUNTY, function(x) {
    get_acs(geography = "county", variables = get_vars$name,
            state = "NC", county = x, geometry = TRUE, output = "wide")
  }),
  rbind
)

wnc_county_data <- wnc_county_data[, names(wnc_county_data) %in% c("NAME", "GEOID", "geometry", get_vars$name)]

```

Column 
-----------------------------------------------------------------------

### Chart A

```{r}
wnc_county_data %>% 
  leaflet(width = "100%") %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>%
  addPolygons(label = NAME, 
              stroke = TRUE,
              weight = 1,
              opacity = .3,
              fillOpacity = .8,
              smoothFactor = .5,
              color = "#070707") 
```

